/*
 * File: app/view/DashboardViewPort.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Dashboard.view.DashboardViewPort', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.dashboardviewport',

    requires: [
        'Ext.toolbar.Toolbar',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.chart.Chart',
        'Ext.util.Point',
        'Ext.chart.axis.Numeric',
        'Ext.chart.axis.Category',
        'Ext.chart.series.Column',
        'Ext.chart.series.Pie',
        'Ext.chart.Legend',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Date'
    ],

    layout: {
        type: 'vbox',
        align: 'stretch'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    flex: 1,
                    itemId: 'basecontainer',
                    items: [
                        {
                            xtype: 'container',
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    itemId: 'txtRepName',
                                    fieldLabel: 'RepositoryName'
                                },
                                {
                                    xtype: 'toolbar',
                                    flex: 1,
                                    items: [
                                        {
                                            xtype: 'button',
                                            text: 'GO'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            padding: 5,
                            items: [
                                {
                                    xtype: 'textfield',
                                    itemId: 'txthomepage',
                                    fieldLabel: 'HmePage'
                                },
                                {
                                    xtype: 'textfield',
                                    itemId: 'txtbranch',
                                    fieldLabel: 'Branch#'
                                },
                                {
                                    xtype: 'textfield',
                                    itemId: 'txtcontributor',
                                    fieldLabel: 'Contributor#'
                                }
                            ]
                        },
                        {
                            xtype: 'tabpanel',
                            activeTab: 0,
                            items: [
                                {
                                    xtype: 'panel',
                                    title: 'Languages',
                                    items: [
                                        {
                                            xtype: 'chart',
                                            height: 400,
                                            itemId: 'languagechart',
                                            width: 800,
                                            animate: true,
                                            insetPadding: 20,
                                            store: 'Language',
                                            axes: [
                                                {
                                                    type: 'Numeric',
                                                    fields: [
                                                        'Size'
                                                    ],
                                                    title: 'Size of code in Byte',
                                                    position: 'left'
                                                },
                                                {
                                                    type: 'Category',
                                                    fields: [
                                                        'Day'
                                                    ],
                                                    title: 'Name of Languages',
                                                    position: 'bottom'
                                                }
                                            ],
                                            series: [
                                                {
                                                    type: 'column',
                                                    tips: {
                                                        trackMouse: true,
                                                        width: 140,
                                                        height: 28,
                                                        renderer: function(storeItem, item) {
                                                                        this.setTitle(storeItem.get('Name') + ': ' + storeItem.get('Size') + ' Byte');
                                                                      }
                                                    },
                                                    axis: 'left',
                                                    xField: 'Name',
                                                    yField: 'Size'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    title: 'ContributorCommits',
                                    dockedItems: [
                                        {
                                            xtype: 'chart',
                                            dock: 'bottom',
                                            height: 400,
                                            itemId: 'comitchart',
                                            width: 600,
                                            shadow: true,
                                            animate: true,
                                            insetPadding: 60,
                                            store: 'ContributorComit',
                                            theme: 'Base:gradients',
                                            series: [
                                                {
                                                    type: 'pie',
                                                    highlight: {
                                                        segment: {
                                                            margin: 20
                                                        }
                                                    },
                                                    label: {
                                                        field: 'Name',
                                                        display: 'rotate',
                                                        contrast: true,
                                                        font: '12px Arial'
                                                    },
                                                    showInLegend: true,
                                                    tips: {
                                                        trackMouse: true,
                                                        width: 140,
                                                        height: 28,
                                                        renderer: function(storeItem, item) {
                                                                      console.log('hi');
                                                                        this.setTitle(storeItem.get('Name') + ': ' + storeItem.get('CommitCount') + 'TotalCommit');
                                                                      }
                                                    },
                                                    angleField: 'CommitCount'
                                                }
                                            ],
                                            legend: {
                                                position: 'right'
                                            }
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Branchs',
                                    items: [
                                        {
                                            xtype: 'container',
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'combobox',
                                                    flex: 1,
                                                    itemId: 'cmbBranch',
                                                    padding: 10,
                                                    fieldLabel: 'Branch',
                                                    labelWidth: 60,
                                                    emptyText: 'Select One Branch',
                                                    selectOnFocus: true,
                                                    forceSelection: true,
                                                    typeAhead: true
                                                },
                                                {
                                                    xtype: 'datefield',
                                                    flex: 1,
                                                    itemId: 'dpbranch',
                                                    fieldLabel: 'Date',
                                                    labelWidth: 60
                                                },
                                                {
                                                    xtype: 'container',
                                                    flex: 2
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            items: [
                                                {
                                                    xtype: 'toolbar',
                                                    items: [
                                                        {
                                                            xtype: 'button',
                                                            itemId: 'btnDiplayChart',
                                                            text: 'DisplayChart'
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ],
                                    dockedItems: [
                                        {
                                            xtype: 'chart',
                                            dock: 'bottom',
                                            height: 220,
                                            itemId: 'branchChart',
                                            padding: 5,
                                            width: 400,
                                            shadow: true,
                                            animate: true,
                                            insetPadding: 20,
                                            store: 'Branch',
                                            axes: [
                                                {
                                                    type: 'Numeric',
                                                    fields: [
                                                        'Count'
                                                    ],
                                                    title: 'Numeric Axis',
                                                    position: 'left'
                                                },
                                                {
                                                    type: 'Category',
                                                    fields: [
                                                        'Day'
                                                    ],
                                                    title: 'Date',
                                                    position: 'bottom'
                                                }
                                            ],
                                            series: [
                                                {
                                                    type: 'column',
                                                    label: {
                                                        display: 'insideEnd',
                                                        field: 'Count',
                                                        color: '#333',
                                                        'text-anchor': 'middle'
                                                    },
                                                    tips: {
                                                        trackMouse: true,
                                                        width: 140,
                                                        height: 28,
                                                        renderer: function(storeItem, item) {
                                                     this.setTitle(storeItem.get('Day') + ': ' + storeItem.get('Count') + ' Commit#');
                                                     }
                                                    },
                                                    xField: 'Day',
                                                    yField: 'Count'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});